//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.06 at 06:19:13 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.netbeans.org/schema/PropertiesSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package chatserver.jaxb;
