/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FBLoginPanel.java
 *
 * Created on Aug 25, 2009, 11:37:42 PM
 */
package gg.msn.ui.facebook;

import facebookchat.common.ErrorCode;
import facebookchat.common.Launcher;
import gg.msn.ui.ChatClientView;
import javax.swing.JOptionPane;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.jdesktop.application.Action;

/**
 *
 * @author Luigi
 */
public class FBLoginPanel extends javax.swing.JPanel {

    private static Log log = LogFactory.getLog(FBLoginPanel.class);
    /** Creates new form FBLoginPanel */
    private final ChatClientView ccv;

    public FBLoginPanel(ChatClientView ccv) {
        initComponents();

        this.ccv = ccv;

    }

    private void connectStart() {
        String email = emailText.getText().trim();
        String pass = passwText.getText().trim();

        /*String email = "username@email.com.cn";
        String pass = "password";*/

        log.debug(email + ":" + pass);
        Launcher launcher = new Launcher();

        int loginErrorCode = launcher.doLogin(email, pass);
        if (loginErrorCode == ErrorCode.Error_Global_NoError) {
            if (launcher.doParseHomePage() == ErrorCode.Error_Global_NoError) {
                Launcher.getBuddyList();

                //keep requesting message from the server
                Thread msgRequester = new Thread(new Runnable() {

                    public void run() {
                        log.debug("Keep requesting...");
                        while (true) {
                            try {
//                                launcher.keepRequesting();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    }
                });
                msgRequester.start();

                //requests buddy list every 90 seconds
                Thread buddyListRequester = new Thread(new Runnable() {

                    public void run() {
                        log.debug("Keep requesting buddylist...");
                        while (true) {
                            log.debug("refresh buddies");
                            try {
                                Launcher.getBuddyList();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }

                            ccv.getMainPanel().updateListWithFACEBOOKContacts();

                            // it's said that the buddy list is updated every 3 minutes at the server end.
                            // we refresh the buddy list every 1.5 minutes
                            try {
                                Thread.sleep(60 * 1000);
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                        }
                    }
                });
                buddyListRequester.start();
                //TODO post
                //Init GUI
                log.debug("Init GUI...");

                ChatClientView.protocol = ChatClientView.FACEBOOK_PROTOCOL;
                ccv.getHelper().showMainPanel();
                log.debug("showed maon panel");
                //必须在getbuddylist之后
//                fbc = new Cheyenne();
//                fbc.setVisible(true);
            }
        } else if (loginErrorCode == ErrorCode.kError_Async_NotLoggedIn) {
            //TODO handle the error derived from this login
            JOptionPane.showMessageDialog(
                    null, "Not logged in, please check your input!",
                    "Not Logged In",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(
                    null, "Not logged in, please check your internet connection!",
                    "Not Logged In",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        passwText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gg.msn.ui.ChatClientApp.class).getContext().getResourceMap(FBLoginPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        emailText.setText(resourceMap.getString("emailText.text")); // NOI18N
        emailText.setName("emailText"); // NOI18N

        passwText.setText(resourceMap.getString("passwText.text")); // NOI18N
        passwText.setName("passwText"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(gg.msn.ui.ChatClientApp.class).getContext().getActionMap(FBLoginPanel.class, this);
        jButton1.setAction(actionMap.get("connect")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void connect() {
        connectStart();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField passwText;
    // End of variables declaration//GEN-END:variables
}
