/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FBLoginPanel.java
 *
 * Created on Aug 25, 2009, 11:37:42 PM
 */
package gg.msn.ui.facebook;

import facebookchat.common.ErrorCode;
import facebookchat.common.FacebookBuddyList;
import facebookchat.common.FacebookManager;
import gg.msn.core.manager.PersistentDataManager;
import gg.msn.ui.ChatClientView;
import gg.msn.ui.facebook.thread.BuddyListRequester;
import gg.msn.ui.facebook.thread.MessageRequester;
import gg.msn.ui.theme.ThemeManager;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.lang.Runnable;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.jdesktop.application.Action;

/**
 *
 * @author Luigi
 */
public class FBLoginPanel extends javax.swing.JPanel {

    private static Log log = LogFactory.getLog(FBLoginPanel.class);
    /** Creates new form FBLoginPanel */
    private final ChatClientView ccv;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        passwText = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        connectionStatusLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gg.msn.ui.ChatClientApp.class).getContext().getResourceMap(FBLoginPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        emailText.setText(resourceMap.getString("emailText.text")); // NOI18N
        emailText.setName("emailText"); // NOI18N

        passwText.setText(resourceMap.getString("passwText.text")); // NOI18N
        passwText.setName("passwText"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(gg.msn.ui.ChatClientApp.class).getContext().getActionMap(FBLoginPanel.class, this);
        loginButton.setAction(actionMap.get("connect")); // NOI18N
        loginButton.setText(resourceMap.getString("loginButton.text")); // NOI18N
        loginButton.setName("loginButton"); // NOI18N

        connectionStatusLabel.setText(resourceMap.getString("connectionStatusLabel.text")); // NOI18N
        connectionStatusLabel.setName("connectionStatusLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwText, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connectionStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(passwText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(loginButton))
                    .addComponent(connectionStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connectionStatusLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField passwText;
    // End of variables declaration//GEN-END:variables

    public FBLoginPanel(ChatClientView ccv) {
        initComponents();
        this.ccv = ccv;

    }

    private void connectStart() {
        String email = emailText.getText().trim();
        String pass = passwText.getText().trim();

        /*String email = "username@email.com.cn";
        String pass = "password";*/

        log.debug(email + ":" + pass);
        final FacebookManager fbManger = new FacebookManager();

        int loginErrorCode = fbManger.doLogin(email, pass);
        if (loginErrorCode == ErrorCode.Error_Global_NoError) {
            if (fbManger.doParseHomePage() == ErrorCode.Error_Global_NoError) {
                int channel = fbManger.findChannel();
                if (channel < 0) {
                    ccv.getHelper().showErrorDialog("Channel not finded!!");
                    return;
                }
                PersistentDataManager.setUid(FacebookManager.uid);
                FacebookManager.getBuddyList();
                ChatClientView.protocol = ChatClientView.FACEBOOK_PROTOCOL;
                PersistentDataManager.setNick(FacebookBuddyList.me.name);

                //keep requesting message from the server
                new Thread(new MessageRequester(ccv, fbManger)).start();

                //requests buddy list every 90 seconds
                new Thread(new BuddyListRequester(ccv)).start();

                //TODO post
                //Init GUI
                log.debug("Init GUI...");

                ccv.getMainPanel().getNickLabel().setText(FacebookBuddyList.me.name);
                ccv.getHelper().showMainPanel();

                log.debug("showed main panel");
                //必须在getbuddylist之后
//                fbc = new Cheyenne();
//                fbc.setVisible(true);
            }
        } else if (loginErrorCode == ErrorCode.kError_Async_NotLoggedIn) {
            //TODO handle the error derived from this login
            JOptionPane.showMessageDialog(
                    null, "Not logged in, please check your input!",
                    "Not Logged In",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(
                    null, "Not logged in, please check your internet connection!",
                    "Not Logged In",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    @Action
    public void connect() {
        loginButton.setVisible(false);
        connectionStatusLabel.setText("connessione in corso ...");
        new Thread(new Runnable() {

            public void run() {
                connectStart();
            }
        }).start();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        super.paintComponent(g2d);
        try {
            g2d.setRenderingHints(new RenderingHints(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR));
//            log.debug("theme : " + ((ChatClientView) ChatClientApp.getApplication().getMainView()).getHelper().getTheme());
            ImageIcon icon = ThemeManager.getTheme().get(ThemeManager.LOGIN_BACKGROUND);

            if (icon != null) {
                Image image = icon.getImage();
                g2d.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            } else {
                log.warn("image " + icon.getDescription() + " not Found");
            }

        } catch (Exception e) {
//            log.debug(e);
        }
    }

    public static void main(String[] args) {
        FacebookManager facebookManager = new FacebookManager();
        facebookManager.doLogin("luigi.ant@email.it", "03021984");
        System.out.println(FacebookManager.facebookGetMethod("http://0.channel35.facebook.com/x/0/false/p_1567835536=-1"));
        System.out.println(FacebookManager.facebookGetMethod("http://www.google.com"));
    }
}
