//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.10.16 at 03:13:08 PM CEST 
//


package chatcommons.datamessage;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.netbeans.xml.schema.datamessagexml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.netbeans.xml.schema.datamessagexml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MESSAGE.Contents }
     * 
     */
    public MESSAGE.Contents createMESSAGEContents() {
        return new MESSAGE.Contents();
    }

    /**
     * Create an instance of {@link MESSAGE.Parameters }
     * 
     */
    public MESSAGE.Parameters createMESSAGEParameters() {
        return new MESSAGE.Parameters();
    }

    /**
     * Create an instance of {@link MESSAGE.Contents.Content }
     * 
     */
    public MESSAGE.Contents.Content createMESSAGEContentsContent() {
        return new MESSAGE.Contents.Content();
    }

    /**
     * Create an instance of {@link MESSAGE }
     * 
     */
    public MESSAGE createMESSAGE() {
        return new MESSAGE();
    }

    /**
     * Create an instance of {@link MESSAGE.Parameters.Parameter }
     * 
     */
    public MESSAGE.Parameters.Parameter createMESSAGEParametersParameter() {
        return new MESSAGE.Parameters.Parameter();
    }

    /**
     * Create an instance of {@link MESSAGE.Receivers }
     * 
     */
    public MESSAGE.Receivers createMESSAGEReceivers() {
        return new MESSAGE.Receivers();
    }

}
